### ISSUE TITLE
Raw dataset

### ISSUE THREAD

**Issue by nightmonkey76** [Nokia-Bell-Labs/olp-gnn#1]
Hi! It seems like you forgot to include the link for downloading the raw datasets. I would appreciate it if I could have the link. Thanks a lot!

**Comment by LouSalaun** [comment]
Hi, thanks for your interest in this project. I will add the link to the datasets soon.

**Comment by LouSalaun** [comment]
The link is added in this commit ed969fde752430c2ba5e2abb9a44551f04f34713
